export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    DASHBOARD1: '/dashboard',
    BOOKS: '/books',
    LIBRARIAN: '/librarian',
    USER: '/user',
    ADD_GROUP: '/group/add-group',
    ADD_USER: '/user/add-user',
    UPDATE_USER: '/user/update-user/:id',
    ADD_BOOKS: '/books/add-books',
    UPDATE_BOOKS: '/books/update-books/:id',
    ADD_LIBRARIAN: '/branch/add-librarian',
    ADD_FACULTY: '/faculty/add-faculty',
    ADD_PROJECT: '/project/add-project',
    LOGOUT: '/logout',
}